// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gksplnijouisdhwyxqwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrc3Bsbmlqb3Vpc2Rod3l4cXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzcyNjEsImV4cCI6MjA3MDgxMzI2MX0.fW47LenFEq_QB3jlk97O1myx590faiESE5RBbRGOqQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});